import { catalogueEvidenceSources } from "../src/lib/catalogue-quality";
import { catalogueDemoSeedManifest } from "../src/lib/catalogue-demo-seed";

function sqlText(value: string) {
  return `'${value.replaceAll("'", "''")}'`;
}

function sqlNullableText(value: string | null | undefined) {
  return value == null || value === "" ? "null" : sqlText(value);
}

function sqlNumber(value: number | null | undefined) {
  return value == null ? "null" : String(value);
}

function sqlBoolean(value: boolean) {
  return value ? "true" : "false";
}

function sqlJson(value: unknown) {
  return `${sqlText(JSON.stringify(value))}::jsonb`;
}

function sqlTextArray(value: string[] | undefined) {
  if (!value) return "null";
  return `array[${value.map(sqlText).join(", ")}]::text[]`;
}

function sqlNumberArray(value: number[] | undefined) {
  if (!value) return "null";
  return `array[${value.join(", ")}]::numeric[]`;
}

function sourceKind(sourceType: "manufacturer" | "retailer" | "internal") {
  if (sourceType === "internal") return "manual";
  return sourceType;
}

function sourceIdQuery(name: string, kind: string) {
  return `(
    select id
    from public.catalogue_sources
    where lower(name) = lower(${sqlText(name)})
      and kind = ${sqlText(kind)}::public.catalogue_source_kind
    limit 1
  )`;
}

function manufacturerIdQuery(name: string | undefined) {
  if (!name) return "null";
  return `(
    select id
    from public.catalogue_manufacturers
    where lower(name) = lower(${sqlText(name)})
    limit 1
  )`;
}

const manifest = catalogueDemoSeedManifest;
const internalSourceName = "DroneCores static demo catalogue";
const internalSourceKind = "manual";

const sourceRows = new Map<
  string,
  { name: string; kind: string; verificationStatus: "verified" | "pending_review" }
>();

sourceRows.set(`${internalSourceName}::${internalSourceKind}`, {
  name: internalSourceName,
  kind: internalSourceKind,
  verificationStatus: "verified",
});

for (const source of catalogueEvidenceSources) {
  const kind = sourceKind(source.sourceType);
  const key = `${source.sourceName}::${kind}`;
  if (!sourceRows.has(key)) {
    sourceRows.set(key, {
      name: source.sourceName,
      kind,
      verificationStatus:
        source.sourceType === "manufacturer" || source.sourceType === "internal"
          ? "verified"
          : "pending_review",
    });
  }
}

const manufacturers = [
  ...new Set(
    manifest.products
      .map((product) => product.manufacturerLabel)
      .filter((value): value is string => Boolean(value)),
  ),
].sort();

const statements: string[] = [
  "-- Generated by scripts/export-demo-catalogue-seed-sql.ts",
  "-- Temporary DroneCores demo/seed catalogue only.",
  "-- Prices are illustrative. No merchant offers are created.",
  "-- Re-running this seed never downgrades a product that has already been promoted to canonical.",
  "begin;",
  "",
];

for (const source of [...sourceRows.values()].sort((a, b) =>
  `${a.kind}:${a.name}`.localeCompare(`${b.kind}:${b.name}`),
)) {
  statements.push(
    `insert into public.catalogue_sources (
  name,
  kind,
  verification_status
) values (
  ${sqlText(source.name)},
  ${sqlText(source.kind)}::public.catalogue_source_kind,
  ${sqlText(source.verificationStatus)}::public.catalogue_verification_status
)
on conflict do nothing;`,
    "",
  );
}

for (const manufacturer of manufacturers) {
  statements.push(
    `insert into public.catalogue_manufacturers (
  name,
  verification_status
) values (
  ${sqlText(manufacturer)},
  'pending_review'
)
on conflict do nothing;`,
    "",
  );
}

for (const product of manifest.products) {
  const identityVerifiedAt =
    product.legacyIdentityStatus === "verified"
      ? sqlText(manifest.reviewedAt)
      : "null";
  const attributes = {
    datasetKey: manifest.datasetKey,
    recordClass: "demo_seed",
    provisionalModelLabel: true,
    market: manifest.market,
    displayCurrency: manifest.displayCurrency,
  };

  statements.push(
    `insert into public.catalogue_products (
  id,
  manufacturer_id,
  model,
  variant,
  display_name,
  category,
  spec_summary,
  weight_grams,
  lifecycle_status,
  verification_status,
  selectable,
  attributes,
  identity_status,
  identity_verified_at,
  record_class
) values (
  ${sqlText(product.id)},
  ${manufacturerIdQuery(product.manufacturerLabel)},
  ${sqlText(product.provisionalModelLabel)},
  null,
  ${sqlText(product.displayName)},
  ${sqlText(product.category)}::public.drone_product_category,
  ${sqlText(product.specSummary)},
  ${sqlNumber(product.weightGrams)},
  'unknown',
  'unverified',
  false,
  ${sqlJson(attributes)},
  ${sqlText(product.legacyIdentityStatus)}::public.catalogue_verification_status,
  ${identityVerifiedAt},
  'demo_seed'
)
on conflict (id) do update set
  manufacturer_id = excluded.manufacturer_id,
  model = excluded.model,
  variant = excluded.variant,
  display_name = excluded.display_name,
  category = excluded.category,
  spec_summary = excluded.spec_summary,
  weight_grams = excluded.weight_grams,
  lifecycle_status = excluded.lifecycle_status,
  verification_status = excluded.verification_status,
  selectable = false,
  attributes = excluded.attributes,
  identity_status = excluded.identity_status,
  identity_verified_at = excluded.identity_verified_at
where public.catalogue_products.record_class = 'demo_seed';`,
    "",
  );

  statements.push(
    `insert into public.catalogue_product_quality_reviews (
  product_id,
  identity_quality_status,
  technical_quality_status,
  product_kind,
  manufacturer_label,
  exact_model_label,
  variant_label,
  price_status,
  illustrative_price_amount,
  illustrative_price_currency,
  human_review_required,
  issues,
  remediation,
  review_dataset,
  reviewed_at
) values (
  ${sqlText(product.id)},
  ${sqlText(product.identityQualityStatus)}::public.catalogue_quality_status,
  ${sqlText(product.technicalQualityStatus)}::public.catalogue_quality_status,
  ${sqlText(product.productKind)}::public.catalogue_product_kind,
  ${sqlNullableText(product.manufacturerLabel)},
  ${sqlNullableText(product.exactModelCandidate)},
  ${sqlNullableText(product.variantCandidate)},
  'illustrative',
  ${sqlNumber(product.illustrativePriceEur)},
  'EUR',
  ${sqlBoolean(product.humanReviewRequired)},
  ${sqlJson(product.issues)},
  ${sqlJson(product.remediation)},
  ${sqlText(manifest.datasetKey)},
  ${sqlText(manifest.reviewedAt)}
)
on conflict (product_id) do update set
  identity_quality_status = excluded.identity_quality_status,
  technical_quality_status = excluded.technical_quality_status,
  product_kind = excluded.product_kind,
  manufacturer_label = excluded.manufacturer_label,
  exact_model_label = excluded.exact_model_label,
  variant_label = excluded.variant_label,
  price_status = excluded.price_status,
  illustrative_price_amount = excluded.illustrative_price_amount,
  illustrative_price_currency = excluded.illustrative_price_currency,
  human_review_required = excluded.human_review_required,
  issues = excluded.issues,
  remediation = excluded.remediation,
  review_dataset = excluded.review_dataset,
  reviewed_at = excluded.reviewed_at
where exists (
  select 1
  from public.catalogue_products p
  where p.id = excluded.product_id
    and p.record_class = 'demo_seed'
);`,
    "",
  );

  const specs = product.specs;
  statements.push(
    `insert into public.catalogue_product_specs (
  product_id,
  frame_size_inches,
  motor_mount_pattern,
  propeller_diameter_inches,
  motor_size_code,
  min_battery_cells,
  max_battery_cells,
  connector,
  esc_input,
  thrust_grams,
  peak_current_amps,
  esc_amps,
  battery_cells,
  battery_capacity_mah,
  video_system,
  camera_video_interface,
  camera_min_voltage_v,
  camera_max_voltage_v,
  camera_width_mm,
  camera_height_mm,
  camera_depth_mm,
  fc_camera_video_interfaces,
  fc_camera_power_voltages_v,
  receiver_protocol,
  receiver_frequency_min_mhz,
  receiver_frequency_max_mhz,
  receiver_min_voltage_v,
  receiver_max_voltage_v,
  receiver_signal_interface,
  receiver_width_mm,
  receiver_height_mm,
  receiver_depth_mm,
  fc_receiver_signal_interfaces,
  fc_receiver_power_voltages_v,
  attributes
)
select
  ${sqlText(product.id)},
  ${sqlNumber(specs.frame_size_inches)},
  ${sqlNullableText(specs.motor_mount_pattern)},
  ${sqlNumber(specs.propeller_diameter_inches)},
  ${sqlNumber(specs.motor_size_code)},
  ${sqlNumber(specs.min_battery_cells)},
  ${sqlNumber(specs.max_battery_cells)},
  ${sqlNullableText(specs.connector)},
  ${sqlNullableText(specs.esc_input)},
  ${sqlNumber(specs.thrust_grams)},
  null,
  ${sqlNumber(specs.esc_amps)},
  ${sqlNumber(specs.battery_cells)},
  ${sqlNumber(specs.battery_capacity_mah)},
  ${sqlNullableText(specs.video_system)},
  ${sqlNullableText(specs.camera_video_interface)},
  ${sqlNumber(specs.camera_min_voltage_v)},
  ${sqlNumber(specs.camera_max_voltage_v)},
  ${sqlNumber(specs.camera_width_mm)},
  ${sqlNumber(specs.camera_height_mm)},
  ${sqlNumber(specs.camera_depth_mm)},
  ${sqlTextArray(specs.fc_camera_video_interfaces)},
  ${sqlNumberArray(specs.fc_camera_power_voltages_v)},
  ${sqlNullableText(specs.receiver_protocol)},
  ${sqlNumber(specs.receiver_frequency_min_mhz)},
  ${sqlNumber(specs.receiver_frequency_max_mhz)},
  ${sqlNumber(specs.receiver_min_voltage_v)},
  ${sqlNumber(specs.receiver_max_voltage_v)},
  ${sqlNullableText(specs.receiver_signal_interface)},
  ${sqlNumber(specs.receiver_width_mm)},
  ${sqlNumber(specs.receiver_height_mm)},
  ${sqlNumber(specs.receiver_depth_mm)},
  ${sqlTextArray(specs.fc_receiver_signal_interfaces)},
  ${sqlNumberArray(specs.fc_receiver_power_voltages_v)},
  ${sqlJson(specs.attributes)}
where exists (
  select 1
  from public.catalogue_products p
  where p.id = ${sqlText(product.id)}
    and p.record_class = 'demo_seed'
)
on conflict (product_id) do update set
  frame_size_inches = excluded.frame_size_inches,
  motor_mount_pattern = excluded.motor_mount_pattern,
  propeller_diameter_inches = excluded.propeller_diameter_inches,
  motor_size_code = excluded.motor_size_code,
  min_battery_cells = excluded.min_battery_cells,
  max_battery_cells = excluded.max_battery_cells,
  connector = excluded.connector,
  esc_input = excluded.esc_input,
  thrust_grams = excluded.thrust_grams,
  peak_current_amps = excluded.peak_current_amps,
  esc_amps = excluded.esc_amps,
  battery_cells = excluded.battery_cells,
  battery_capacity_mah = excluded.battery_capacity_mah,
  video_system = excluded.video_system,
  camera_video_interface = excluded.camera_video_interface,
  camera_min_voltage_v = excluded.camera_min_voltage_v,
  camera_max_voltage_v = excluded.camera_max_voltage_v,
  camera_width_mm = excluded.camera_width_mm,
  camera_height_mm = excluded.camera_height_mm,
  camera_depth_mm = excluded.camera_depth_mm,
  fc_camera_video_interfaces = excluded.fc_camera_video_interfaces,
  fc_camera_power_voltages_v = excluded.fc_camera_power_voltages_v,
  receiver_protocol = excluded.receiver_protocol,
  receiver_frequency_min_mhz = excluded.receiver_frequency_min_mhz,
  receiver_frequency_max_mhz = excluded.receiver_frequency_max_mhz,
  receiver_min_voltage_v = excluded.receiver_min_voltage_v,
  receiver_max_voltage_v = excluded.receiver_max_voltage_v,
  receiver_signal_interface = excluded.receiver_signal_interface,
  receiver_width_mm = excluded.receiver_width_mm,
  receiver_height_mm = excluded.receiver_height_mm,
  receiver_depth_mm = excluded.receiver_depth_mm,
  fc_receiver_signal_interfaces = excluded.fc_receiver_signal_interfaces,
  fc_receiver_power_voltages_v = excluded.fc_receiver_power_voltages_v,
  attributes = excluded.attributes
where exists (
  select 1
  from public.catalogue_products p
  where p.id = excluded.product_id
    and p.record_class = 'demo_seed'
);`,
    "",
  );
}

statements.push(
  `delete from public.catalogue_product_images i
using public.catalogue_products p
where i.product_id = p.id
  and p.record_class = 'demo_seed'
  and i.provenance = 'DroneCores demo seed Phase A';`,
  "",
);

for (const product of manifest.products) {
  if (!product.image) continue;

  statements.push(
    `insert into public.catalogue_product_images (
  product_id,
  image_url,
  source_url,
  alt_text,
  exact_model_verified,
  verification_status,
  provenance,
  primary_image
)
select
  ${sqlText(product.id)},
  ${sqlText(product.image.src)},
  ${sqlText(product.image.sourceUrl)},
  ${sqlText(product.image.alt)},
  false,
  'pending_review',
  'DroneCores demo seed Phase A',
  true
where exists (
  select 1
  from public.catalogue_products p
  where p.id = ${sqlText(product.id)}
    and p.record_class = 'demo_seed'
);`,
    "",
  );
}

const internalSourceId = sourceIdQuery(internalSourceName, internalSourceKind);

for (const product of manifest.products) {
  statements.push(
    `insert into public.catalogue_product_sources (
  product_id,
  source_id,
  external_product_id,
  source_url,
  verification_status,
  exact_model_association,
  retrieved_at,
  metadata
)
select
  ${sqlText(product.id)},
  ${internalSourceId},
  ${sqlText(product.id)},
  null,
  'verified',
  false,
  ${sqlText(manifest.reviewedAt)},
  ${sqlJson({
    datasetKey: manifest.datasetKey,
    recordClass: "demo_seed",
  })}
where exists (
  select 1
  from public.catalogue_products p
  where p.id = ${sqlText(product.id)}
    and p.record_class = 'demo_seed'
)
on conflict (source_id, external_product_id) do update set
  imported_at = now(),
  verification_status = excluded.verification_status,
  exact_model_association = excluded.exact_model_association,
  retrieved_at = excluded.retrieved_at,
  metadata = excluded.metadata;`,
    "",
  );
}

statements.push(
  `delete from public.catalogue_import_batches
where file_name = 'catalogue-demo-seed-phase-a'
  and source_id = ${internalSourceId};`,
  "",
  `insert into public.catalogue_import_batches (
  source_id,
  file_name,
  status,
  total_rows,
  valid_rows,
  invalid_rows,
  notes,
  reviewed_at,
  import_kind
) values (
  ${internalSourceId},
  'catalogue-demo-seed-phase-a',
  'imported',
  ${manifest.products.length},
  ${manifest.products.length},
  0,
  'Temporary evidence-first demo seed. Not a production catalogue and not a market-price import.',
  ${sqlText(manifest.reviewedAt)},
  'products'
);`,
  "",
);

for (const [index, product] of manifest.products.entries()) {
  const normalizedData = {
    productId: product.id,
    recordClass: "demo_seed",
    identityQualityStatus: product.identityQualityStatus,
    technicalQualityStatus: product.technicalQualityStatus,
    priceStatus: "illustrative",
    illustrativePriceEur: product.illustrativePriceEur,
  };

  statements.push(
    `insert into public.catalogue_import_rows (
  batch_id,
  row_number,
  proposed_product_id,
  raw_data,
  normalized_data,
  status,
  validation_errors,
  duplicate_product_id,
  reviewed_at
) values (
  (
    select id
    from public.catalogue_import_batches
    where file_name = 'catalogue-demo-seed-phase-a'
      and source_id = ${internalSourceId}
    order by created_at desc
    limit 1
  ),
  ${index + 1},
  ${sqlText(product.id)},
  ${sqlJson(product.rawProduct)},
  ${sqlJson(normalizedData)},
  'imported',
  '[]'::jsonb,
  ${sqlText(product.id)},
  ${sqlText(manifest.reviewedAt)}
);`,
    "",
  );
}

for (const field of manifest.evidence) {
  const verifiedAt =
    field.verificationStatus === "verified"
      ? sqlNullableText(field.verifiedAt)
      : "null";
  const sourceId = sourceIdQuery(field.sourceName, field.sourceKind);

  statements.push(
    `insert into public.catalogue_spec_evidence (
  product_id,
  field_key,
  value,
  unit,
  value_semantics,
  source_id,
  source_url,
  authority,
  exact_model_association,
  verification_status,
  retrieved_at,
  verified_at,
  conditions,
  caveats,
  conflict_group
)
select
  ${sqlText(field.productId)},
  ${sqlText(String(field.field))},
  ${sqlJson(field.value)},
  ${sqlNullableText(field.unit)},
  null,
  ${sourceId},
  ${sqlNullableText(field.sourceUrl)},
  ${sqlText(field.authority)}::public.catalogue_evidence_authority,
  ${sqlBoolean(field.exactModelAssociation)},
  ${sqlText(field.verificationStatus)}::public.catalogue_verification_status,
  ${sqlNullableText(field.retrievedAt)},
  ${verifiedAt},
  ${sqlJson(field.conditions ?? {})},
  ${sqlNullableText(field.caveats)},
  null
where exists (
  select 1
  from public.catalogue_products p
  where p.id = ${sqlText(field.productId)}
    and p.record_class = 'demo_seed'
)
on conflict do nothing;`,
    "",
  );
}

statements.push(
  "-- Demo prices intentionally do not create catalogue_offers rows.",
  "-- Pair evidence intentionally remains empty until exact manufacturer-supported combinations are reviewed.",
  "commit;",
  "",
);

process.stdout.write(statements.join("\n"));
