/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiBuildRouteImport } from './routes/ai-build'
import { Route as CreateCustomBuildRouteImport } from './routes/create-custom-build'
import { Route as PreBuiltRouteImport } from './routes/pre-built'
import { Route as StartRouteImport } from './routes/start'
import { Route as TemplatesRouteImport } from './routes/templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBuildRoute = AiBuildRouteImport.update({
  id: '/ai-build',
  path: '/ai-build',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCustomBuildRoute = CreateCustomBuildRouteImport.update({
  id: '/create-custom-build',
  path: '/create-custom-build',
  getParentRoute: () => rootRouteImport,
} as any)
const PreBuiltRoute = PreBuiltRouteImport.update({
  id: '/pre-built',
  path: '/pre-built',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-build': typeof AiBuildRoute
  '/create-custom-build': typeof CreateCustomBuildRoute
  '/pre-built': typeof PreBuiltRoute
  '/start': typeof StartRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-build': typeof AiBuildRoute
  '/create-custom-build': typeof CreateCustomBuildRoute
  '/pre-built': typeof PreBuiltRoute
  '/start': typeof StartRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-build': typeof AiBuildRoute
  '/create-custom-build': typeof CreateCustomBuildRoute
  '/pre-built': typeof PreBuiltRoute
  '/start': typeof StartRoute
  '/templates': typeof TemplatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-build'
    | '/create-custom-build'
    | '/pre-built'
    | '/start'
    | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-build'
    | '/create-custom-build'
    | '/pre-built'
    | '/start'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/ai-build'
    | '/create-custom-build'
    | '/pre-built'
    | '/start'
    | '/templates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiBuildRoute: typeof AiBuildRoute
  CreateCustomBuildRoute: typeof CreateCustomBuildRoute
  PreBuiltRoute: typeof PreBuiltRoute
  StartRoute: typeof StartRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-build': {
      id: '/ai-build'
      path: '/ai-build'
      fullPath: '/ai-build'
      preLoaderRoute: typeof AiBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-custom-build': {
      id: '/create-custom-build'
      path: '/create-custom-build'
      fullPath: '/create-custom-build'
      preLoaderRoute: typeof CreateCustomBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-built': {
      id: '/pre-built'
      path: '/pre-built'
      fullPath: '/pre-built'
      preLoaderRoute: typeof PreBuiltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiBuildRoute: AiBuildRoute,
  CreateCustomBuildRoute: CreateCustomBuildRoute,
  PreBuiltRoute: PreBuiltRoute,
  StartRoute: StartRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
